language: java

cache:
  directories:
  - $HOME/.m2

addons:
  apt:
    packages: mediainfo

matrix:
  include:
    - os: linux
    - os: osx
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.3

install: mvn external:install

script: mvn verify -B -V -P testing
