# The strategy with these matrixes are to test both old and new versions of operating systems
# and Java, to ensure we don't break old things and that newer things continue to work

branches:
  only:
    - master

jobs:
  include:
    - os: osx
      osx_image: xcode11
      language: java
      script: mvn verify -P testing-macos
    - os: osx
      osx_image: xcode11.1
      language: java
      script: mvn verify -P testing-macos
    - os: osx
      osx_image: xcode11.2
      language: java
      script: mvn verify -P testing-macos
    - os: osx
      osx_image: xcode11.3
      language: java
      script: mvn verify -P testing-macos
    - os: osx
      osx_image: xcode11.4
      language: java
      script: mvn verify -P testing-macos

install: mvn external:install
