name: 'Changelog'
on: [push, pull_request]

jobs:
  changelog:
    if: |
      github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dangoslen/dependabot-changelog-helper@v3
        with:
          activationLabel: 'dependencies'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Changelog"