name: PullRequestConflicting

on:
  push:
    branches: [ main ]
  pull_request:
    types: [synchronize]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check if prs are dirty
      uses: eps1lon/actions-label-merge-conflict@releases/2.x
      id: check
      with:
        dirtyLabel: "conflicting"
        repoToken: "${{ secrets.GITHUB_TOKEN  }}"
        continueOnMissingPermissions: true
        commentOnDirty: '@dependabot rebase'
        commentOnClean: 'Conflicts have been resolved. A maintainer will take a look shortly.'